// Full list of Surahs with metadata
export const surahMetadata = [
  { number: 1, name: "الفاتحة", verses: 7, type: "Meccan", english: "Al-Fatiha" },
  { number: 2, name: "البقرة", verses: 286, type: "Medinan", english: "Al-Baqarah" },
  { number: 3, name: "آل عمران", verses: 200, type: "Medinan", english: "Al-Imran" },
  { number: 4, name: "النساء", verses: 176, type: "Medinan", english: "An-Nisa" },
  { number: 5, name: "المائدة", verses: 120, type: "Medinan", english: "Al-Ma'idah" },
  { number: 6, name: "الأنعام", verses: 165, type: "Meccan", english: "Al-An'am" },
  { number: 7, name: "الأعراف", verses: 206, type: "Meccan", english: "Al-A'raf" },
  { number: 8, name: "الأنفال", verses: 75, type: "Medinan", english: "Al-Anfal" },
  { number: 9, name: "التوبة", verses: 129, type: "Medinan", english: "At-Tawbah" },
  { number: 10, name: "يونس", verses: 109, type: "Meccan", english: "Yunus" },
  { number: 11, name: "هود", verses: 123, type: "Meccan", english: "Hud" },
  { number: 12, name: "يوسف", verses: 111, type: "Meccan", english: "Yusuf" },
  { number: 13, name: "الرعد", verses: 43, type: "Medinan", english: "Ar-Ra'd" },
  { number: 14, name: "إبراهيم", verses: 52, type: "Meccan", english: "Ibrahim" },
  { number: 15, name: "الحجر", verses: 99, type: "Meccan", english: "Al-Hijr" },
  { number: 16, name: "النحل", verses: 128, type: "Meccan", english: "An-Nahl" },
  { number: 17, name: "الإسراء", verses: 111, type: "Meccan", english: "Al-Isra" },
  { number: 18, name: "الكهف", verses: 110, type: "Meccan", english: "Al-Kahf" },
  { number: 19, name: "مريم", verses: 98, type: "Meccan", english: "Maryam" },
  { number: 20, name: "طه", verses: 135, type: "Meccan", english: "Ta-Ha" },
  { number: 21, name: "الأنبياء", verses: 112, type: "Meccan", english: "Al-Anbiya" },
  { number: 22, name: "الحج", verses: 78, type: "Medinan", english: "Al-Hajj" },
  { number: 23, name: "المؤمنون", verses: 118, type: "Meccan", english: "Al-Mu'minun" },
  { number: 24, name: "النور", verses: 64, type: "Medinan", english: "An-Nur" },
  { number: 25, name: "الفرقان", verses: 77, type: "Meccan", english: "Al-Furqan" },
  { number: 26, name: "الشعراء", verses: 227, type: "Meccan", english: "Ash-Shu'ara" },
  { number: 27, name: "النمل", verses: 93, type: "Meccan", english: "An-Naml" },
  { number: 28, name: "القصص", verses: 88, type: "Meccan", english: "Al-Qasas" },
  { number: 29, name: "العنكبوت", verses: 69, type: "Meccan", english: "Al-Ankabut" },
  { number: 30, name: "الروم", verses: 60, type: "Meccan", english: "Ar-Rum" },
  { number: 31, name: "لقمان", verses: 34, type: "Meccan", english: "Luqman" },
  { number: 32, name: "السجدة", verses: 30, type: "Meccan", english: "As-Sajdah" },
  { number: 33, name: "الأحزاب", verses: 73, type: "Medinan", english: "Al-Ahzab" },
  { number: 34, name: "سبأ", verses: 54, type: "Meccan", english: "Saba" },
  { number: 35, name: "فاطر", verses: 45, type: "Meccan", english: "Fatir" },
  { number: 36, name: "يس", verses: 83, type: "Meccan", english: "Ya-Sin" },
  { number: 37, name: "الصافات", verses: 182, type: "Meccan", english: "As-Saffat" },
  { number: 38, name: "ص", verses: 88, type: "Meccan", english: "Sad" },
  { number: 39, name: "الزمر", verses: 75, type: "Meccan", english: "Az-Zumar" },
  { number: 40, name: "غافر", verses: 85, type: "Meccan", english: "Ghafir" },
  { number: 41, name: "فصلت", verses: 54, type: "Meccan", english: "Fussilat" },
  { number: 42, name: "الشورى", verses: 53, type: "Meccan", english: "Ash-Shura" },
  { number: 43, name: "الزخرف", verses: 89, type: "Meccan", english: "Az-Zukhruf" },
  { number: 44, name: "الدخان", verses: 59, type: "Meccan", english: "Ad-Dukhan" },
  { number: 45, name: "الجاثية", verses: 37, type: "Meccan", english: "Al-Jathiyah" },
  { number: 46, name: "الأحقاف", verses: 35, type: "Meccan", english: "Al-Ahqaf" },
  { number: 47, name: "محمد", verses: 38, type: "Medinan", english: "Muhammad" },
  { number: 48, name: "الفتح", verses: 29, type: "Medinan", english: "Al-Fath" },
  { number: 49, name: "الحجرات", verses: 18, type: "Medinan", english: "Al-Hujurat" },
  { number: 50, name: "ق", verses: 45, type: "Meccan", english: "Qaf" },
  { number: 51, name: "الذاريات", verses: 60, type: "Meccan", english: "Ad-Dhariyat" },
  { number: 52, name: "الطور", verses: 49, type: "Meccan", english: "At-Tur" },
  { number: 53, name: "النجم", verses: 62, type: "Meccan", english: "An-Najm" },
  { number: 54, name: "القمر", verses: 55, type: "Meccan", english: "Al-Qamar" },
  { number: 55, name: "الرحمن", verses: 78, type: "Medinan", english: "Ar-Rahman" },
  { number: 56, name: "الواقعة", verses: 96, type: "Meccan", english: "Al-Waqi'ah" },
  { number: 57, name: "الحديد", verses: 29, type: "Medinan", english: "Al-Hadid" },
  { number: 58, name: "المجادلة", verses: 22, type: "Medinan", english: "Al-Mujadila" },
  { number: 59, name: "الحشر", verses: 24, type: "Medinan", english: "Al-Hashr" },
  { number: 60, name: "الممتحنة", verses: 13, type: "Medinan", english: "Al-Mumtahanah" },
  { number: 61, name: "الصف", verses: 14, type: "Medinan", english: "As-Saff" },
  { number: 62, name: "الجمعة", verses: 11, type: "Medinan", english: "Al-Jumu'ah" },
  { number: 63, name: "المنافقون", verses: 11, type: "Medinan", english: "Al-Munafiqun" },
  { number: 64, name: "التغابن", verses: 18, type: "Medinan", english: "At-Taghabun" },
  { number: 65, name: "الطلاق", verses: 12, type: "Medinan", english: "At-Talaq" },
  { number: 66, name: "التحريم", verses: 12, type: "Medinan", english: "At-Tahrim" },
  { number: 67, name: "الملك", verses: 30, type: "Meccan", english: "Al-Mulk" },
  { number: 68, name: "القلم", verses: 52, type: "Meccan", english: "Al-Qalam" },
  { number: 69, name: "الحاقة", verses: 52, type: "Meccan", english: "Al-Haqqah" },
  { number: 70, name: "المعارج", verses: 44, type: "Meccan", english: "Al-Ma'arij" },
  { number: 71, name: "نوح", verses: 28, type: "Meccan", english: "Nuh" },
  { number: 72, name: "الجن", verses: 28, type: "Meccan", english: "Al-Jinn" },
  { number: 73, name: "المزمل", verses: 20, type: "Meccan", english: "Al-Muzzammil" },
  { number: 74, name: "المدثر", verses: 56, type: "Meccan", english: "Al-Muddaththir" },
  { number: 75, name: "القيامة", verses: 40, type: "Meccan", english: "Al-Qiyamah" },
  { number: 76, name: "الإنسان", verses: 31, type: "Medinan", english: "Al-Insan" },
  { number: 77, name: "المرسلات", verses: 50, type: "Meccan", english: "Al-Mursalat" },
  { number: 78, name: "النبأ", verses: 40, type: "Meccan", english: "An-Naba" },
  { number: 79, name: "النازعات", verses: 46, type: "Meccan", english: "An-Nazi'at" },
  { number: 80, name: "عبس", verses: 42, type: "Meccan", english: "Abasa" },
  { number: 81, name: "التكوير", verses: 29, type: "Meccan", english: "At-Takwir" },
  { number: 82, name: "الإنفطار", verses: 19, type: "Meccan", english: "Al-Infitar" },
  { number: 83, name: "المطففين", verses: 36, type: "Meccan", english: "Al-Mutaffifin" },
  { number: 84, name: "الإنشقاق", verses: 25, type: "Meccan", english: "Al-Inshiqaq" },
  { number: 85, name: "البروج", verses: 22, type: "Meccan", english: "Al-Buruj" },
  { number: 86, name: "الطارق", verses: 17, type: "Meccan", english: "At-Tariq" },
  { number: 87, name: "الأعلى", verses: 19, type: "Meccan", english: "Al-A'la" },
  { number: 88, name: "الغاشية", verses: 26, type: "Meccan", english: "Al-Ghashiyah" },
  { number: 89, name: "الفجر", verses: 30, type: "Meccan", english: "Al-Fajr" },
  { number: 90, name: "البلد", verses: 20, type: "Meccan", english: "Al-Balad" },
  { number: 91, name: "الشمس", verses: 15, type: "Meccan", english: "Ash-Shams" },
  { number: 92, name: "الليل", verses: 21, type: "Meccan", english: "Al-Lail" },
  { number: 93, name: "الضحى", verses: 11, type: "Meccan", english: "Ad-Duha" },
  { number: 94, name: "الشرح", verses: 8, type: "Meccan", english: "Ash-Sharh" },
  { number: 95, name: "التين", verses: 8, type: "Meccan", english: "At-Tin" },
  { number: 96, name: "العلق", verses: 19, type: "Meccan", english: "Al-Alaq" },
  { number: 97, name: "القدر", verses: 5, type: "Meccan", english: "Al-Qadr" },
  { number: 98, name: "البينة", verses: 8, type: "Medinan", english: "Al-Bayyinah" },
  { number: 99, name: "الزلزلة", verses: 8, type: "Medinan", english: "Az-Zalzalah" },
  { number: 100, name: "العاديات", verses: 11, type: "Meccan", english: "Al-Adiyat" },
  { number: 101, name: "القارعة", verses: 11, type: "Meccan", english: "Al-Qari'ah" },
  { number: 102, name: "التكاثر", verses: 8, type: "Meccan", english: "At-Takathur" },
  { number: 103, name: "العصر", verses: 3, type: "Meccan", english: "Al-Asr" },
  { number: 104, name: "الهمزة", verses: 9, type: "Meccan", english: "Al-Humazah" },
  { number: 105, name: "الفيل", verses: 5, type: "Meccan", english: "Al-Fil" },
  { number: 106, name: "قريش", verses: 4, type: "Meccan", english: "Quraish" },
  { number: 107, name: "الماعون", verses: 7, type: "Meccan", english: "Al-Ma'un" },
  { number: 108, name: "الكوثر", verses: 3, type: "Meccan", english: "Al-Kawthar" },
  { number: 109, name: "الكافرون", verses: 6, type: "Meccan", english: "Al-Kafirun" },
  { number: 110, name: "النصر", verses: 3, type: "Medinan", english: "An-Nasr" },
  { number: 111, name: "المسد", verses: 5, type: "Meccan", english: "Al-Masad" },
  { number: 112, name: "الإخلاص", verses: 4, type: "Meccan", english: "Al-Ikhlas" },
  { number: 113, name: "الفلق", verses: 5, type: "Meccan", english: "Al-Falaq" },
  { number: 114, name: "الناس", verses: 6, type: "Meccan", english: "An-Nas" }
];

// Juz Amma Text (Partial - for offline use)
export const juzAmmaText: Record<number, string> = {
  1: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ۝ الرَّحْمَنِ الرَّحِيمِ ۝ مَالِكِ يَوْمِ الدِّينِ ۝ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ۝ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ۝ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
  112: "قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ",
  113: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ",
  114: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلَهِ النَّاسِ ۝ مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الْجِنَّةِ وَالنَّاسِ",
  // In a real app we would dump the full JSON here, but for this mock I'll just add a few more famous ones from Juz Amma
  108: "إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ ۝ فَصَلِّ لِرَبِّكَ وَانْحَرْ ۝ إِنَّ شَانِئَكَ هُوَ الْأَبْتَرُ",
  109: "قُلْ يَا أَيُّهَا الْكَافِرُونَ ۝ لَا أَعْبُدُ مَا تَعْبُدُونَ ۝ وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ ۝ وَلَا أَنَا عَابِدٌ مَّا عَبَدتُّمْ ۝ وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ ۝ لَكُمْ دِينُكُمْ وَلِيَ دِينِ",
  110: "إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ ۝ وَرَأَيْتَ النَّاسَ يَدْخُلُونَ فِي دِينِ اللَّهِ أَفْوَاجًا ۝ فَسَبِّحْ بِحَمْدِ رَبِّكَ وَاسْتَغْفِرْهُ ۚ إِنَّهُ كَانَ تَوَّابًا",
  111: "تَبَّتْ يَدَا أَبِي لَهَبٍ وَتَبَّ ۝ مَا أَغْنَىٰ عَنْهُ مَالُهُ وَمَا كَسَبَ ۝ سَيَصْلَىٰ نَارًا ذَاتَ لَهَبٍ ۝ وَامْرَأَتُهُ حَمَّالَةَ الْحَطَبِ ۝ فِي جِيدِهَا حَبْلٌ مِّن مَّسَدٍ",
};
